trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ANSIBLE_HOST_KEY_CHECKING: "False"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      python -m pip install --upgrade pip
      pip install ansible
    displayName: 'Install Ansible'

  - task: DownloadSecureFile@1
    name: sshkey
    inputs:
      secureFile: 'id_rsa'  # Upload this via Pipelines > Library > Secure Files

  - script: |
      chmod 600 $(sshkey.secureFilePath)
      ansible-playbook ansible/lighttpd-playbook.yml \
        -i ansible/inventory.ini \
        --private-key $(sshkey.secureFilePath)
    displayName: 'Run Ansible Playbook'
